name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Install poetry
        shell: bash
        run: pipx install poetry==1.2.2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"
          cache: "poetry"
      - name: Install python dependencies
        shell: bash
        run: poetry install
      - name: Build results page
        shell: bash
        run: poetry run python -m build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./out"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
